// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// do_magic_cpp
int do_magic_cpp(const int x);
RcppExport SEXP domagic_do_magic_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type x(xSEXP);
    __result = Rcpp::wrap(do_magic_cpp(x));
    return __result;
END_RCPP
}
