sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:marutter/rrutter # For R
  - sudo apt-get update -qq

install: 
  # R
  - sudo apt-get install -qq r-base r-base-dev
  - sudo Rscript install_r_packages.R
  # pdflatex, for R vignettes
  - sudo apt-get install -qq texlive

script: 
 # C++
 - qmake
 - make
 - ./domagic
 # Prepare R, must be removed manually, even though these are also mentioned in `.gitignore`
 - rm .gitignore
 - rm .Rhistory
 - rm src/.gitignore
 - rm .travis.yml
 - rm -rf .git
 - rm -rf ..Rcheck
 - rm *.o
 # R
 - R CMD check .

after_failure:
 # fatal error: Rcpp.h: No such file or directory
 - find / -name 'Rcpp.h'
 # R logs
 - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp98_rcpp/..Rcheck/00install.out


