sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:marutter/rrutter # For R
  - sudo apt-get update -qq

install: 
  - sudo apt-get install r-base r-base-dev # For R
  - sudo apt-get install -qq lyx     # For pdflatex
  - sudo apt-get install -qq texlive # For pdflatex

script: 
 # C++
 - ./build_cpp.sh
 # R wants all non-R files gone...
 - ./clean.sh
 - sudo Rscript install_r_packages.R
 - rm .gitignore
 - rm src/.gitignore
 - rm .travis.yml
 - rm -rf .git
 - rm -rf ..Rcheck
 # Now R is ready to go
 - R CMD check .

after_script:
 - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp98_rcpp/..Rcheck/00install.out

