sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:marutter/rrutter # For R
  - sudo apt-get update -qq

install: 
  # R
  - sudo apt-get install -qq r-base r-base-dev # For R
  - sudo apt-get install -qq lyx     # For pdflatex
  - sudo apt-get install -qq texlive # For pdflatex
  - sudo Rscript install_r_packages.R

script: 
 # C++
 - qmake
 - make
 - ./domagic
 # R
 - R CMD check .

after_failure:
 # fatal error: Rcpp.h: No such file or directory
 - find / -name 'Rcpp.h'
 # R logs
 - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp98_rcpp/..Rcheck/00install.out


