# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Does magic
#' @param x Input
#' @return Magic value
#' @export
do_magic_cpp <- function(x) {
    .Call('domagic_do_magic_cpp', PACKAGE = 'domagic', x)
}

